export const medicationCategories = [
  {
    name: "General health",
    categories: [
      "Pain Relief and Management",
      "Cold & flu",
      "Allergies",
      "Antimalarials",
      "Bone, Joint & Muscular Care",
      "Eye Care",
      "Ear Care",
      "Cardiovascular care",
      "Respiratory Care",
      "Metabolics",
      "Gastrointestinals",
      "Cholesterol Care",
      "Prostrate Health",
      "STDs & Sexual Care",
      "Hemorrhoids, Fissures & Fistula",
      "Mental Health/CNS",
      "Cough",
      "Addiction Management",
      "Rashes and Skin Scare",
      "Beauty products",
    ]
  },
  {
    name: "Sexual Wellness/Fertility",
    categories: [
      "Family Planning & Condoms",
      "Lubricants & Massage Gels",
      "Erectile dysfunctuion",
      "Fertility Support",
      "Sex Toys",
      "Sexual Health supplements",
      "Hormonal Therapies",
      "Performance Enhancers",
      "Test and Diagnostics",
    ]
  },
  {
    name: "Personal Care",
    categories: [
      "Skin Care",
      "Hair Care",
      "Oral Care",
      "Baby Care",
      "Elderly Care",
      "Women Care",
      "Premenstrual Syndrome",
      "Pregnancy",
      "Postmenopausal Syndrome",
      "Men Care",
      "Family Care",
      "Cosmetics",
      "Home test and monitoring",
      "Foot care",
      "Hearing aids and amplifiers",
    ]
  },
  {
    name: "Nutrition, Fitness & Supplements",
    categories: [
      "Vitamins & Mineral Supplements",
      "Protein Supplements",
      "Omega & Fish Oil",
      "Pregnancy & Breastfeeding",
      "Immunity Boosters",
      "Sleep Aid",
      "Weight Management",
      "Body building",
      "Nutritional Drinks",
      "Other Health Food & Drinks",
      "Probiotics",
      "Neurological disorders",
      "Kidney and Liver cleansers",
      "Bitters and Tonics",
      "Blood sugar control",
    ]
  },
  {
    name: "Devices, Surgicals & First Aid",
    categories: [
      " Masks (N95, Surgical masks)",
      "Face Shield",
      "Mucus extractor",
      "Breast pump",
      "BP Monitors",
      "Nebulizers & Vaporizers",
      "Oximeters & Pedometers",
      "Vital Signs Monitors & Wearables",
      "Oxygen Concentrators & Cans",
      "Weighing Scales",
      "Thermometers",
      "IR Thermometers",
      "Body Massager",
      "Diabetes Monitors",
      "Test Strips & Lancets",
      "Syringes & Pens",
      "Mobility Equipments",
      "Exercise Equipements",
      "Practice",
      "Stethoscopes",
      "Sphignomanometer",
      "Clinical diagnostic equipments",
    ]
  },
  {
    name: "Orthopaedics",
    categories: [
      "Tapes & Bandages",
      "Plaster of Paris (POP)",
      "Crutches",
    ]
  },
  {
    name: "Dressings & Wound Care",
    categories: [
      "Supports & Braces",
      "Neck & Shoulder Support",
      "Knee & Leg Support",
      "Back & Abdomen Support",
      "Ankle & Foot Support",
      "Hand & Wrist Braces",
      "Arm & Elbow Support",
      "Cervical Pillows",
      "Compression support & sleeves",
      "Heel support",
      "Speculum",
      "Swab sticks",
    ]
  },
  {
    name: "Geriatric Care",
    categories: [
      "Neurological/Memory enhancers",
      "Urinary health",
      "Adult pampers",
      "Ophthalmic drugs",
    ]
  },
  {
    name: "Paediatrics",
    categories: [
      "Teething mixtures",
      "Multivitamins and Supplements",
      "Brain development",
      "Diapers",
      "Baby wash",
      "Baby Hair and Skin Care",
      "Paediatric Food and formular",
      "Child Protection",
      "Paediatric Health care"
    ]
  },
]